<?php
/**
 * A google file download tracker that add a onclick attribute for anchors generated by change:download.
 * In project.xml :
 *	<modules>
 *		<media>
 *			<additionnalDownloadAttributesBuilders>
 *				<entry>markergas_DownloadTracker</entry>
 *			</additionnalDownloadAttributesBuilders>
 *		</media>
 *	</modules>
 * @see PHPTAL_Php_Attribute_CHANGE_download 
 */
class markergas_DownloadTracker implements f_DownloadAttributeBuilder
{
	/**
	 * @param f_persistentdocument_PersistentDocument $media
	 * @param string $class
	 * @return array<String, String>
	 */
	function getAttributes($media, $class)
	{
		$path = f_Locale::translate('&modules.markergas.frontoffice.MediaDownloadPath;')."/".$media->getDocumentService()->getPathOf($media)."/".$media->getLabel();
		return array("class" => "link download", "onclick" => "javascript: pageTracker._trackPageview ('".str_replace("'", "\\'", $path)."');");
	}
}